### ISSUE TITLE
庄园 帮喂小鸡 好友列表不能全选， 后面的文本框什么意思也没注释

### ISSUE THREAD

**Issue by minglu6** [lazy-immortal/Sesame#10]
### 程序版本 / 框架版本 / 模块版本

v1.6.0.7

### 系统版本 / Android版本

android 14

### 详细描述问题发生的具体原因

庄园 帮喂小鸡 好友列表不能全选  

### 提供模块问题 Log 或必要 Log

这个很好复现 就不贴图了 日志也没报错，就是页面不可选

**Comment by lazy-immortal** [comment]
填数字的列表全选什么？又不是打勾！
