### ISSUE TITLE
支付宝闪退

### ISSUE THREAD

**Issue by Lkarthus** [lazy-immortal/Sesame#13]
### 程序版本 / 框架版本 / 模块版本

程序版本：10.6.66.8000 框架版本：LSPatch：1.8.5 模块版本：V1.6.1

### 系统版本 / Android版本

HyperOS1.0.10.0 Android14

### 详细描述问题发生的具体原因

支付宝嵌入模块之后，打开就闪退。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by lazy-immortal** [comment]
不支持内置，符合预期行为。
