### ISSUE TITLE
提示芝麻关门：四十大盗，模块无法连接到支付宝

### ISSUE THREAD

**Issue by Lkarthus** [lazy-immortal/Sesame#16]
### 程序版本 / 框架版本 / 模块版本

程序版本：10.6.66.8000 框架版本：LSPatch：1.9.2 模块版本：V1.6.1

### 系统版本 / Android版本

HyperOS1.0.10.0 Android14

### 详细描述问题发生的具体原因

本地模式使用模块不能启用，打开模块一直没有支付宝的信息
![微信截图_20241207092838](https://github.com/user-attachments/assets/47f763df-5a14-47ef-bb25-508179eb8c49)
![微信截
![微信截图_20241207092915](https://github.com/user-attachments/assets/98ff900a-b7b5-437d-a016-84863fa2398f)
图_20241207092853](https://github.com/user-attachments/assets/9997069e-bab9-4bb1-a90c-ac35093669c0)
![微信截图_20241207092928](https://github.com/user-attachments/assets/4f532195-9b70-4fbe-acee-fd10194f800a)
![微信截图_20241207093012](https://github.com/user-attachments/assets/f5a3789b-fedd-4345-b98c-18ba94076880)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)
09:19:39.365 RUNTIME: ApplicationHook, hook matchVersion successfully
09:19:39.365 RUNTIME: ApplicationHook, hook login successfully
09:19:39.366 RUNTIME: ApplicationHook, hook service onCreate successfully
09:19:39.367 RUNTIME: ApplicationHook, hook MiscUtils successfully
09:19:39.367 RUNTIME: ApplicationHook, load success: com.eg.android.AlipayGphone
09:19:39.611 RUNTIME: ApplicationHook, Activity onResume
09:19:40.038 RUNTIME: ApplicationHook, Service onCreate
09:19:52.279 RUNTIME: 加载APP配置
09:19:52.284 RUNTIME: FileUtil, statisticsFile.json文件不存在
09:19:52.285 RUNTIME: Statistics, 初始化 statistics.json
09:19:59.293 RUNTIME: 加载APP配置
09:19:59.294 RUNTIME: FileUtil, [statistics]读:true;写:true
09:20:07.021 RUNTIME: ApplicationHook, Activity onResume
09:20:11.553 RUNTIME: ApplicationHook, Activity onResume
09:20:20.559 RUNTIME: 加载APP配置
09:20:20.564 RUNTIME: FileUtil, [statistics]读:true;写:true
09:20:24.024 RUNTIME: ConfigV2, 开始加载配置
09:20:24.024 RUNTIME: 加载配置: 默认
09:20:24.025 RUNTIME: ConfigV2, 初始新配置: 默认
09:20:24.028 RUNTIME: ConfigV2, 加载配置结束
09:21:02.395 RUNTIME: 加载APP配置
09:21:02.397 RUNTIME: FileUtil, [statistics]读:true;写:true
09:21:11.204 RUNTIME: 加载APP配置
09:21:11.206 RUNTIME: FileUtil, [statistics]读:true;写:true
09:21:15.518 RUNTIME: 加载APP配置
09:21:15.520 RUNTIME: FileUtil, [statistics]读:true;写:true
09:21:17.884 RUNTIME: ApplicationHook, Activity onResume
09:21:22.654 RUNTIME: ApplicationHook, hook matchVersion successfully
09:21:22.657 RUNTIME: ApplicationHook, hook login successfully
09:21:22.657 RUNTIME: ApplicationHook, hook service onCreate successfully
09:21:22.659 RUNTIME: ApplicationHook, hook MiscUtils successfully
09:21:22.659 RUNTIME: ApplicationHook, load success: com.eg.android.AlipayGphone
09:21:22.888 RUNTIME: ApplicationHook, Activity onResume
09:21:23.080 RUNTIME: ApplicationHook, Service onCreate
09:21:35.165 RUNTIME: 加载APP配置
09:21:35.180 RUNTIME: FileUtil, [statistics]读:true;写:true
09:21:44.629 RUNTIME: 加载APP配置
09:21:44.631 RUNTIME: FileUtil, [statistics]读:true;写:true
09:21:50.578 RUNTIME: 加载APP配置
09:21:50.580 RUNTIME: FileUtil, [statistics]读:true;写:true
09:21:53.590 RUNTIME: ConfigV2, 开始加载配置
09:21:53.590 RUNTIME: 加载配置: 默认
09:21:53.597 RUNTIME: ConfigV2, 格式化配置: 默认
09:21:53.598 RUNTIME: ConfigV2, 加载配置结束
09:22:28.373 RUNTIME: 保存配置: 默认
09:22:28.405 RUNTIME: 加载APP配置
09:22:28.407 RUNTIME: FileUtil, [statistics]读:true;写:true
09:22:37.964 RUNTIME: 加载APP配置
09:22:37.966 RUNTIME: FileUtil, [statistics]读:true;写:true
09:22:40.342 RUNTIME: ApplicationHook, Activity onResume
09:22:45.698 RUNTIME: ApplicationHook, hook matchVersion successfully
09:22:45.701 RUNTIME: ApplicationHook, hook login successfully
09:22:45.702 RUNTIME: ApplicationHook, hook service onCreate successfully
09:22:45.704 RUNTIME: ApplicationHook, hook MiscUtils successfully
09:22:45.704 RUNTIME: ApplicationHook, load success: com.eg.android.AlipayGphone
09:22:46.154 RUNTIME: ApplicationHook, Activity onResume
09:22:46.596 RUNTIME: ApplicationHook, Service onCreate
09:22:50.087 RUNTIME: ApplicationHook, hook matchVersion successfully
09:22:50.090 RUNTIME: ApplicationHook, hook login successfully
09:22:50.091 RUNTIME: ApplicationHook, hook service onCreate successfully
09:22:50.093 RUNTIME: ApplicationHook, hook MiscUtils successfully
09:22:50.093 RUNTIME: ApplicationHook, load success: com.eg.android.AlipayGphone
09:22:50.658 RUNTIME: ApplicationHook, Activity onResume
09:22:51.211 RUNTIME: ApplicationHook, Service onCreate
09:22:55.190 RUNTIME: 加载APP配置
09:22:55.196 RUNTIME: FileUtil, [statistics]读:true;写:true
09:22:55.937 RUNTIME: ApplicationHook, hook matchVersion successfully
09:22:55.942 RUNTIME: ApplicationHook, hook login successfully
09:22:55.944 RUNTIME: ApplicationHook, hook service onCreate successfully
09:22:55.949 RUNTIME: ApplicationHook, hook MiscUtils successfully
09:22:55.949 RUNTIME: ApplicationHook, load success: com.eg.android.AlipayGphone
09:22:59.670 RUNTIME: ConfigV2, 开始加载配置
09:22:59.670 RUNTIME: 加载配置: 默认
09:22:59.678 RUNTIME: ConfigV2, 格式化配置: 默认
09:22:59.679 RUNTIME: ConfigV2, 加载配置结束
09:23:03.072 RUNTIME: ApplicationHook, Service onCreate
09:23:16.214 RUNTIME: 保存配置: 默认
09:23:16.241 RUNTIME: 加载APP配置
09:23:16.243 RUNTIME: FileUtil, [statistics]读:true;写:true
09:23:22.041 RUNTIME: 加载APP配置
09:23:22.042 RUNTIME: FileUtil, [statistics]读:true;写:true
09:23:27.759 RUNTIME: ApplicationHook, Activity onResume
09:23:43.652 RUNTIME: 加载APP配置
09:23:43.655 RUNTIME: FileUtil, [statistics]读:true;写:true
09:23:48.454 RUNTIME: 加载APP配置
09:23:48.455 RUNTIME: FileUtil, [statistics]读:true;写:true
09:24:15.003 RUNTIME: 加载APP配置
09:24:15.006 RUNTIME: FileUtil, [statistics]读:true;写:true
09:24:17.344 RUNTIME: ConfigV2, 开始加载配置
09:24:17.344 RUNTIME: 加载配置: 默认
09:24:17.352 RUNTIME: ConfigV2, 加载配置结束
09:24:27.658 RUNTIME: 加载APP配置
09:24:27.660 RUNTIME: FileUtil, [statistics]读:true;写:true
09:29:00.614 RUNTIME: 加载APP配置
09:29:00.626 RUNTIME: FileUtil, [statistics]读:true;写:true
09:29:07.628 RUNTIME: ConfigV2, 开始加载配置
09:29:07.628 RUNTIME: 加载配置: 默认
09:29:07.637 RUNTIME: ConfigV2, 加载配置结束
09:29:22.755 RUNTIME: ApplicationHook, hook matchVersion successfully
09:29:22.756 RUNTIME: ApplicationHook, hook login successfully
09:29:22.756 RUNTIME: ApplicationHook, hook service onCreate successfully
09:29:22.758 RUNTIME: ApplicationHook, hook MiscUtils successfully
09:29:22.758 RUNTIME: ApplicationHook, load success: com.eg.android.AlipayGphone
09:29:23.000 RUNTIME: ApplicationHook, Activity onResume
09:29:23.271 RUNTIME: ApplicationHook, Service onCreate
09:30:02.223 RUNTIME: 加载APP配置
09:30:02.226 RUNTIME: FileUtil, [statistics]读:true;写:true
09:30:16.177 RUNTIME: 加载APP配置
09:30:16.179 RUNTIME: FileUtil, [statistics]读:true;写:true
</code></pre></details>

**Comment by lazy-immortal** [comment]
``

**Comment by xiaowei456** [comment]
> 芝麻开门条件：(非内置包 & 无芝麻糊X)

还是这么周么？内置你就的限制，

**Comment by Memor2804014143** [comment]
我的不内置也一样用不了。。。
